/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EuropeanCallOptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contractSize"
      | "exercised"
      | "expirationTime"
      | "expireOption"
      | "factory"
      | "holder"
      | "isExercisable"
      | "issuer"
      | "payPremium"
      | "setHolder"
      | "status"
      | "strikeAsset"
      | "strikePrice"
      | "underlyingAsset"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OptionCreated"
      | "OptionExercised"
      | "OptionExpired"
      | "PremiumPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "contractSize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "exercised", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "expirationTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expireOption",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "holder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isExercisable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "issuer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payPremium",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHolder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "strikeAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "strikePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingAsset",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "contractSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exercised", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expirationTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expireOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "holder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isExercisable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payPremium", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHolder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strikeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strikePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingAsset",
    data: BytesLike
  ): Result;
}

export namespace OptionCreatedEvent {
  export type InputTuple = [issuer: AddressLike, holder: AddressLike];
  export type OutputTuple = [issuer: string, holder: string];
  export interface OutputObject {
    issuer: string;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionExercisedEvent {
  export type InputTuple = [exerciser: AddressLike];
  export type OutputTuple = [exerciser: string];
  export interface OutputObject {
    exerciser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionExpiredEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PremiumPaidEvent {
  export type InputTuple = [payer: AddressLike, amount: BigNumberish];
  export type OutputTuple = [payer: string, amount: bigint];
  export interface OutputObject {
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EuropeanCallOption extends BaseContract {
  connect(runner?: ContractRunner | null): EuropeanCallOption;
  waitForDeployment(): Promise<this>;

  interface: EuropeanCallOptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contractSize: TypedContractMethod<[], [bigint], "view">;

  exercised: TypedContractMethod<[], [void], "nonpayable">;

  expirationTime: TypedContractMethod<[], [bigint], "view">;

  expireOption: TypedContractMethod<[], [void], "nonpayable">;

  factory: TypedContractMethod<[], [string], "view">;

  holder: TypedContractMethod<[], [string], "view">;

  isExercisable: TypedContractMethod<[], [boolean], "view">;

  issuer: TypedContractMethod<[], [string], "view">;

  payPremium: TypedContractMethod<
    [premium: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHolder: TypedContractMethod<[_holder: AddressLike], [void], "nonpayable">;

  status: TypedContractMethod<[], [bigint], "view">;

  strikeAsset: TypedContractMethod<[], [string], "view">;

  strikePrice: TypedContractMethod<[], [bigint], "view">;

  underlyingAsset: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contractSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "exercised"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "expirationTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "expireOption"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "holder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isExercisable"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payPremium"
  ): TypedContractMethod<[premium: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHolder"
  ): TypedContractMethod<[_holder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "strikeAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "strikePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "underlyingAsset"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OptionCreated"
  ): TypedContractEvent<
    OptionCreatedEvent.InputTuple,
    OptionCreatedEvent.OutputTuple,
    OptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OptionExercised"
  ): TypedContractEvent<
    OptionExercisedEvent.InputTuple,
    OptionExercisedEvent.OutputTuple,
    OptionExercisedEvent.OutputObject
  >;
  getEvent(
    key: "OptionExpired"
  ): TypedContractEvent<
    OptionExpiredEvent.InputTuple,
    OptionExpiredEvent.OutputTuple,
    OptionExpiredEvent.OutputObject
  >;
  getEvent(
    key: "PremiumPaid"
  ): TypedContractEvent<
    PremiumPaidEvent.InputTuple,
    PremiumPaidEvent.OutputTuple,
    PremiumPaidEvent.OutputObject
  >;

  filters: {
    "OptionCreated(address,address)": TypedContractEvent<
      OptionCreatedEvent.InputTuple,
      OptionCreatedEvent.OutputTuple,
      OptionCreatedEvent.OutputObject
    >;
    OptionCreated: TypedContractEvent<
      OptionCreatedEvent.InputTuple,
      OptionCreatedEvent.OutputTuple,
      OptionCreatedEvent.OutputObject
    >;

    "OptionExercised(address)": TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;
    OptionExercised: TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;

    "OptionExpired(address)": TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;
    OptionExpired: TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;

    "PremiumPaid(address,uint256)": TypedContractEvent<
      PremiumPaidEvent.InputTuple,
      PremiumPaidEvent.OutputTuple,
      PremiumPaidEvent.OutputObject
    >;
    PremiumPaid: TypedContractEvent<
      PremiumPaidEvent.InputTuple,
      PremiumPaidEvent.OutputTuple,
      PremiumPaidEvent.OutputObject
    >;
  };
}
