/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OptionFactory {
  export type OptionInfoStruct = {
    optionAddress: AddressLike;
    issuer: AddressLike;
    holder: AddressLike;
    createdAt: BigNumberish;
    exists: boolean;
  };

  export type OptionInfoStructOutput = [
    optionAddress: string,
    issuer: string,
    holder: string,
    createdAt: bigint,
    exists: boolean
  ] & {
    optionAddress: string;
    issuer: string;
    holder: string;
    createdAt: bigint;
    exists: boolean;
  };
}

export interface OptionFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createOption"
      | "getAllOptions"
      | "getMatchableOptions"
      | "getOptionCount"
      | "getOptionInfo"
      | "getUserCreatedOptions"
      | "matchOption"
      | "optionIndex"
      | "options"
      | "userCreatedOptions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OptionCreated" | "OptionMatched"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createOption",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllOptions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchableOptions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCreatedOptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchOption",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "optionIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "options",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userCreatedOptions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchableOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCreatedOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optionIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "options", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userCreatedOptions",
    data: BytesLike
  ): Result;
}

export namespace OptionCreatedEvent {
  export type InputTuple = [
    optionId: BigNumberish,
    optionAddress: AddressLike,
    issuer: AddressLike,
    underlyingAsset: AddressLike,
    strikeAsset: AddressLike,
    strikePrice: BigNumberish,
    expirationTime: BigNumberish,
    contractSize: BigNumberish
  ];
  export type OutputTuple = [
    optionId: bigint,
    optionAddress: string,
    issuer: string,
    underlyingAsset: string,
    strikeAsset: string,
    strikePrice: bigint,
    expirationTime: bigint,
    contractSize: bigint
  ];
  export interface OutputObject {
    optionId: bigint;
    optionAddress: string;
    issuer: string;
    underlyingAsset: string;
    strikeAsset: string;
    strikePrice: bigint;
    expirationTime: bigint;
    contractSize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionMatchedEvent {
  export type InputTuple = [
    optionId: BigNumberish,
    optionAddress: AddressLike,
    holder: AddressLike
  ];
  export type OutputTuple = [
    optionId: bigint,
    optionAddress: string,
    holder: string
  ];
  export interface OutputObject {
    optionId: bigint;
    optionAddress: string;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OptionFactory extends BaseContract {
  connect(runner?: ContractRunner | null): OptionFactory;
  waitForDeployment(): Promise<this>;

  interface: OptionFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createOption: TypedContractMethod<
    [
      _underlyingAsset: AddressLike,
      _strikeAsset: AddressLike,
      _strikePrice: BigNumberish,
      _expirationTime: BigNumberish,
      _contractSize: BigNumberish
    ],
    [[bigint, string] & { optionId: bigint; optionAddress: string }],
    "nonpayable"
  >;

  getAllOptions: TypedContractMethod<[], [string[]], "view">;

  getMatchableOptions: TypedContractMethod<[], [string[]], "view">;

  getOptionCount: TypedContractMethod<[], [bigint], "view">;

  getOptionInfo: TypedContractMethod<
    [_optionAddress: AddressLike],
    [OptionFactory.OptionInfoStructOutput],
    "view"
  >;

  getUserCreatedOptions: TypedContractMethod<
    [_user: AddressLike],
    [string[]],
    "view"
  >;

  matchOption: TypedContractMethod<
    [_optionAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  optionIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  options: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        optionAddress: string;
        issuer: string;
        holder: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  userCreatedOptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createOption"
  ): TypedContractMethod<
    [
      _underlyingAsset: AddressLike,
      _strikeAsset: AddressLike,
      _strikePrice: BigNumberish,
      _expirationTime: BigNumberish,
      _contractSize: BigNumberish
    ],
    [[bigint, string] & { optionId: bigint; optionAddress: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllOptions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMatchableOptions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getOptionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOptionInfo"
  ): TypedContractMethod<
    [_optionAddress: AddressLike],
    [OptionFactory.OptionInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCreatedOptions"
  ): TypedContractMethod<[_user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "matchOption"
  ): TypedContractMethod<[_optionAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "optionIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "options"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        optionAddress: string;
        issuer: string;
        holder: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userCreatedOptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "OptionCreated"
  ): TypedContractEvent<
    OptionCreatedEvent.InputTuple,
    OptionCreatedEvent.OutputTuple,
    OptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OptionMatched"
  ): TypedContractEvent<
    OptionMatchedEvent.InputTuple,
    OptionMatchedEvent.OutputTuple,
    OptionMatchedEvent.OutputObject
  >;

  filters: {
    "OptionCreated(uint256,address,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      OptionCreatedEvent.InputTuple,
      OptionCreatedEvent.OutputTuple,
      OptionCreatedEvent.OutputObject
    >;
    OptionCreated: TypedContractEvent<
      OptionCreatedEvent.InputTuple,
      OptionCreatedEvent.OutputTuple,
      OptionCreatedEvent.OutputObject
    >;

    "OptionMatched(uint256,address,address)": TypedContractEvent<
      OptionMatchedEvent.InputTuple,
      OptionMatchedEvent.OutputTuple,
      OptionMatchedEvent.OutputObject
    >;
    OptionMatched: TypedContractEvent<
      OptionMatchedEvent.InputTuple,
      OptionMatchedEvent.OutputTuple,
      OptionMatchedEvent.OutputObject
    >;
  };
}
